server:
  port: 8002
spring:
  application:
    name: payment-process-service
  datasource:
    url: jdbc:postgresql://localhost:5452/finpay_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: payment-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.payment_process_service.dto.PaymentInitiationEvent
        spring.json.use.type.headers: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

account:
  service:
    url: http://localhost:8003
