server:
  port: 8004

spring:
  application:
    name: reconciliation-service
  datasource:
    url: jdbc:postgresql://localhost:5452/finpay_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/